### ISSUE TITLE
大佬666！在学习MauiBlazor  看大佬项目学到好多！再咨询个困扰很久的问题

### ISSUE THREAD

**Issue by lhtuling** [Yu-Core/SwashbucklerDiary#10]
大佬的项目为什么打包后只有20多M
我自己搞的项目各种设置到最后也要有100多m   
要么是10M左右的不能用的apk  安装打开后就闪退

**Comment by Yu-Core** [comment]
默认打包是包含arm64和x64的，只打包arm64会减少差不多一半的体积。剪裁我也开启了。-r android-arm64 -p:PublishTrimmed=true
写了一个特别简陋的安卓打包，平时我一般用这个。https://github.com/Yu-Core/MAUIAndroidReleaseTool

**Comment by lhtuling** [comment]
> 默认打包是包含arm64和x64的，只打包arm64会减少差不多一半的体积。剪裁我也开启了。-r android-arm64 -p:PublishTrimmed=true 写了一个特别简陋的安卓打包，平时我一般用这个。https://github.com/Yu-Core/MAUIAndroidReleaseTool

太感谢了   搞定了   困扰好久了！
