### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by KleinPan** [Yu-Core/SwashbucklerDiary#11]
请问只用maui实现按理说可以支持readme上的功能，为什么还需要blazor等web技术呢？

**Comment by Yu-Core** [comment]
Razor语法相较于Xaml更加方便高效
样式上也更自由，而且可以借助Blazor乃至web的生态
Blazor有很多开源的风格统一的组件库，MAUI的话太少，而且也基本都是收费的
未来如果移植到网页端也更方便
当然，纯MAUI的话在性能上要比MAUI Blazor好。

**Comment by KleinPan** [comment]
明白了，我准备fork一下，研究纯用maui试试
