### ISSUE TITLE
日记能否支持视频或者音频类

### ISSUE THREAD

**Issue by zzmzaizai** [Yu-Core/SwashbucklerDiary#12]
增加多媒体类的随手记录会更有意义

还请考虑下这方面的需求

**Comment by Yu-Core** [comment]
之前有过这个打算。但是老是写不好，漏洞百出。有时间我再研究研究。

**Comment by zzmzaizai** [comment]
> 之前有过这个打算。但是老是写不好，漏洞百出。有时间我再研究研究。

加油加油，这个是真不错。给你加星

**Comment by zzmzaizai** [comment]
> 抱歉，久等了，新的版本0.83.7已支持音频、视频

赞 ：）
