### ISSUE TITLE
请问成就这些数据是怎么在浏览器的indexdb里初始化的呢？

### ISSUE THREAD

**Issue by Hdurian-CH** [Yu-Core/SwashbucklerDiary#22]
学习一下

**Comment by Yu-Core** [comment]
是指日记这些数据吗，存在sqlite里的，sqlite文件存在indexedDB里。
初始化时候，把indexedDB的内容同步到内存中的文件系统
https://github.com/Yu-Core/SwashbucklerDiary/blob/master/src/SwashbucklerDiary.WebAssembly/wwwroot/js/fileSystem.js

**Comment by Yu-Core** [comment]
应该是这个吧
https://github.com/Yu-Core/SwashbucklerDiary/blob/master/src/SwashbucklerDiary.WebAssembly/Extensions/ServiceCollectionExtensions/AddGlobal.cs

https://github.com/Yu-Core/SwashbucklerDiary/blob/master/src/SwashbucklerDiary.WebAssembly/Services/Data/AchievementService/AchievementService.cs#L18

**Comment by Yu-Core** [comment]
抱歉，这个不太清楚。你可以到masa blazor的qq群或者微信群问问。
