### ISSUE TITLE
.NET 8 MAUI的打包问题

### ISSUE THREAD

**Issue by ZCH-czc** [Yu-Core/SwashbucklerDiary#24]
请教一下在.net 8 中，maui打包Windows平台exe的时候有遇到这个吗？RuntimeIdentifier“win10-x64”

**Comment by Yu-Core** [comment]
刚试了一下
用命令行打包exe没发现问题
可能你缺少-p:RuntimeIdentifierOverride=win10-x64
https://learn.microsoft.com/zh-cn/dotnet/maui/windows/deployment/publish-unpackaged-cli?view=net-maui-8.0#publish
