### ISSUE TITLE
大家一起参与开发吧

### ISSUE THREAD

**Issue by winstonwxj** [Yu-Core/SwashbucklerDiary#25]
仓主，建议可以把开发路线或者优先级比较高的一些功能点简单梳理罗列一下，这样方便大家参与进来

**Comment by Yu-Core** [comment]
有道理，我近期整理一下

**Comment by Yu-Core** [comment]
不好意思，久等了
简单整理了一下，有不足之处还望补充
https://github.com/users/Yu-Core/projects/2
