### ISSUE TITLE
[Bug Report]: 添加图片、音频、视频的错误行为

### ISSUE THREAD

**Issue by yanecc** [Yu-Core/SwashbucklerDiary#54]
**Describe the bug**
在日记中添加图片、视频会唤起闪传分享窗口、两个照片选择弹窗；在日记中添加音频会唤起两个文件管理器。（需要依次退出两次）

**To Reproduce**
在日记中添加图片、音频、视频。

**Expected behavior**
不唤起闪传分享弹窗，仅弹出一次媒体选择窗口

**Smartphone :**
 - Device: Nubia Z50
 - OS: MyOS 14
 - Version 0.91.6

**Comment by yanecc** [comment]
发现添加图片、音频、视频均有较高概率发生闪退，闪退之后再次弹出文件管理器窗口。

https://github.com/Yu-Core/SwashbucklerDiary/assets/89304297/a5b7cc79-5af2-44b4-9ae8-72d344708163

https://github.com/Yu-Core/SwashbucklerDiary/assets/89304297/2278d39e-66da-4a08-9bd2-145ef1bbb547

**Comment by yanecc** [comment]
> 写了一个demo，麻烦你测试一下，辛苦了
> 
> 下载，解压，安装 [com.companyname.filepickertestdemo-Signed.zip](https://github.com/user-attachments/files/16052814/com.companyname.filepickertestdemo-Signed.zip)

图片2、文件2、视频2工作正常

**Comment by Yu-Core** [comment]
1.2.2版本已经修复了。建议你尝试一下
