### ISSUE TITLE
[Feature request]: 请问可以添加标签筛选功能嘛

### ISSUE THREAD

**Issue by SugarWong97** [Yu-Core/SwashbucklerDiary#55]
你好！这个日记的UI很好看，用起来感觉很好。

但是关于标签的功能，我看好像只支持了`单标签`，请问可以实现`标签多选`吗？

> 即：同时选中某些`标签`，筛选出同时带有这些标签的日记。

**Comment by SugarWong97** [comment]
好~谢谢您的回复~祝您生活愉快~

**Comment by Yu-Core** [comment]
1.2.2版本已支持

**Comment by SugarWong97** [comment]
刚刚在Windows平台上试了一下，真的非常感激您~
