### ISSUE TITLE
[Feature request]: 图片与正文分离

### ISSUE THREAD

**Issue by wildgooseL** [Yu-Core/SwashbucklerDiary#59]
希望图片及其它附件可以在正文末尾单独列出，而不是混排在正文中。
这样有两点好处：
1. 减小排版压力；
2. 保持正文简洁；
3. 手机屏幕较小，插入正文的图片浏览效率低；而放在末尾，用宫格方式排列的话会更方便浏览。
图文分离不排斥混排，前者作为可选项即可。

示例图：一本日记界面
![Screenshot_20240715_110125_com hihonor appmarket_edit_81424706324458](https://github.com/user-attachments/assets/7c365073-2e1e-44de-9b78-0ea1d74b0319)

**Comment by Yu-Core** [comment]
暂时没有这种打算。这种方式与markdown不相符。

**Comment by aabolo** [comment]
无所谓吧，也可以使用文本模式浏览的
