### ISSUE TITLE
[Feature request]: 建议添加 搜索结果的高亮提示，改为主界面的搜索页就开始高亮提示

### ISSUE THREAD

**Issue by MAKER555** [Yu-Core/SwashbucklerDiary#68]
### Description

主界面的搜索界面就开始高亮提示，方便直接查看对应的关键词的位置。一搜到底，都会提示，直到退出本次搜索。

**Comment by MAKER555** [comment]
现在是主界面搜索，筛选出含有关键词的单条，但是点进去没有高亮提示，需要在单条日记里再次搜索才会出现高亮，会比较繁琐，希望在主界面搜索直接就高亮提示，如果看单条日记A并不是我需要看的，那么返回主界面的搜索结果里，再点到日记B，依旧可以有关键词高亮提示，这样会更方便，一遍搜索，全部都高亮，直到退出本次搜索。

**Comment by Yu-Core** [comment]
感谢建议，下个版本会有

**Comment by Yu-Core** [comment]
https://github.com/Yu-Core/SwashbucklerDiary/commit/b5b4b44437dea0e1fd360ca6c4734a12bb7d40da Completed
