### ISSUE TITLE
[Bug Report]: 你好，1.2.2版本的windows和android版都有的用户昵称和签名修改无效的问题。

### ISSUE THREAD

**Issue by yuhoocom** [Yu-Core/SwashbucklerDiary#69]
### Description

目前的1.2.2版本的windows和android版本，更新以后，以前设定的用户昵称以及签名都变回了默认，并且出现了修改无效的问题。
![动画](https://github.com/user-attachments/assets/e0228041-8422-4ee2-bbbb-1df99c0da037)

### Version with bug

1.2.2

### Affected platforms

Android, Windows

### Affected platform versions

Android 14; Windows 11 23H2

**Comment by Yu-Core** [comment]
感谢反馈，下个版本会修复

**Comment by Yu-Core** [comment]
https://github.com/Yu-Core/SwashbucklerDiary/commit/6760c2440c9c694a1fc22d68722903db5e13a660 Completed
