### ISSUE TITLE
[Feature request]: 要求支持表格就完美了，可以当个笔记本用！(有时候记东西需要用到表格)

### ISSUE THREAD

**Issue by kufx** [Yu-Core/SwashbucklerDiary#70]
### Description

要求支持表格就完美了，可以当个笔记本用！(有时候记东西需要用到表格)
谢谢

### Applications with this feature

有时候记东西需要用到表格

**Comment by Yu-Core** [comment]
默认的插入表格感觉不太好用，只能插入3×3的，所以就没有在工具栏添加表格的按钮，我尝试优化优化。

**Comment by Yu-Core** [comment]
Completed https://github.com/Yu-Core/SwashbucklerDiary/commit/c05038e8b67ab0108001bedf1b02fdc202b6c5e0
