### ISSUE TITLE
[Optimize request]: 优化Android上的软键盘输入弹起界面调整实现

### ISSUE THREAD

**Issue by Memoyu** [Yu-Core/SwashbucklerDiary#74]
Description
我在个人项目中采用了相同的软键盘输入弹起界面调整实现时，出现了些许偏差；
经过一番折腾，发现官方有更为简便的实现方式，且相对更可靠。
相关文档： [Android 上的软键盘输入模式](https://learn.microsoft.com/zh-cn/dotnet/maui/android/platform-specifics/soft-keyboard-input-mode?view=net-maui-8.0)

Supported platforms
No response

Applications with this feature
No response

Related technologies
No response

**Comment by Yu-Core** [comment]
用过，正常情况下可以用。
但开启了EdgeToEdge后，它这个就失效了，这与Android本身的bug有关
