### ISSUE TITLE
[Feature request]: 关于插入的音频

### ISSUE THREAD

**Issue by bing996** [Yu-Core/SwashbucklerDiary#75]
### Description

插入的音频在日记打开的时候能自动播放可就太Nice了！！

**Comment by Yu-Core** [comment]
很好的建议
考虑到一篇日记可能有多个音频、视频，因此，应该只播放第一个
准备添加一个设置

**Comment by Yu-Core** [comment]
Completed https://github.com/Yu-Core/SwashbucklerDiary/commit/bfd4f6bc005d15278d24b662c9cbeb0a507c892d
