### ISSUE TITLE
[交流贴] NET 9 的 blazor.webassembly.js 兼容性问题是怎么处理的？

### ISSUE THREAD

**Issue by vitash** [Yu-Core/SwashbucklerDiary#79]
这两天测了一下 Android 8，发现一直在 loading 中，一路查找从 Maui 到 aspnetcore （ https://github.com/dotnet/maui/issues/25862 ，https://github.com/dotnet/maui/issues/24278 ， https://github.com/dotnet/aspnetcore/issues/59090  ）。发现他们真的不想管这个问题（就想用最新），有计划是 NET10 处理一下兼容性，感觉就悬。

就以这种兼容性，IOS 16（2022年9月）、安卓API 31（2021年10月）都不行，对 Maui 来说真的难以接受。

另一个吐槽：XAML （https://github.com/dotnet/maui/discussions/13043 ）促使我逃离 Maui，Blazor 是最后的选择了。

看到项目文件有自己的 blazor.webassembly.js，这是什么时候构建的？我也想直接拿来试用了，刚刚尝试构建 aspnetcore 的 Components，卡住了。

**Comment by Yu-Core** [comment]
大概七天前，提交时构建的https://github.com/Yu-Core/SwashbucklerDiary/commit/963a46c961b18a96955878d4857cb27037b01111

自己构建的话也不是很难
下载aspnetcore源码
安装node.js
src/Components/Shared.JS/tsconfig.json 把target改为ES2019
https://github.com/dotnet/aspnetcore/blob/v9.0.0/src/Components/README.md#building-aspnet-core-components 只执行npm相关的就行，dotnet的不用跑，可能会有点小问题，不过搜索引擎都能解决
编译出来的js在src/Components/Web.JS/dist

**Comment by vitash** [comment]
强 👍，如果 NET 10没计划支持呢，那得自己构建了

**Comment by LuohuaRain** [comment]
> 发现他们真的不想管这个问题（就想用最新），有计划是 NET10 处理一下兼容性，感觉就悬。

有这个 `有计划是 NET10 处理一下兼容性` 的source吗？

thanks.

**Comment by vitash** [comment]
这里已经有比较好的解决方案了：https://github.com/dotnet/maui/discussions/27327

左边的 https://github.com/dotnet/maui/issues/24278 Milestone有写 `.NET 10 Planning`

**Comment by Yu-Core** [comment]
.NET10 https://github.com/Yu-Core/BlazorJSFileES2019
